@baseUrl = http://localhost:4000

### Signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "name": "Hasinthaka Admin",
  "email": "hasi@ceylongems.com",
  "password": "12341234",
  "phone": "1234527890",
  "address": "123 Main St",
  "role":"ADMIN"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "Passw0rd!"
}
